#! /bin/bash
File=''
Riff=''
Measure=''
Strings=''
Tuning=''

for arg in "$@"; do
  shift
  case "$arg" in
    "--help")       set -- "$@" "-h" ;;
    "--file")       set -- "$@" "-f" ;;
    "--riff")       set -- "$@" "-r" ;;
    "--measure")    set -- "$@" "-m" ;;
    "--strings")    set -- "$@" "-s" ;;
    "--tuning")     set -- "$@" "-t" ;;
    *)              set -- "$@" "$arg"
  esac
done

while getopts ":hf:m:s:r:t:" option; do
   case "${option}" in
    h)
      python src/main.py -h
      exit 1
      ;;
    f) File="$OPTARG";;
    r) Riff="$OPTARG";;
    m) Measure="$OPTARG";;
    s) Strings="$OPTARG";;
    t) Tuning="$OPTARG";;
  esac
done

python src/main.py -f "$File" -r "$Riff" -m "$Measure" -s "$Strings" -t "$Tuning"